-- USERS
CREATE TABLE USERS (
  ID           NVARCHAR(36) PRIMARY KEY,
  LOGIN_NAME   NVARCHAR(255) NOT NULL,
  EMAIL        NVARCHAR(255) NOT NULL,
  LAST_NAME    NVARCHAR(255) NOT NULL,
  USER_TYPE    NVARCHAR(50)  NOT NULL,
  STATUS       NVARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',

  FIRST_NAME   NVARCHAR(255),
  VALID_FROM   DATE,
  VALID_TO     DATE,
  COMPANY      NVARCHAR(255),
  COUNTRY      NVARCHAR(2),
  CITY         NVARCHAR(255),

  IAS_LAST_MODIFIED TIMESTAMP,

  CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_UTCTIMESTAMP,
  UPDATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_UTCTIMESTAMP
);

ALTER TABLE USERS ADD CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL);
ALTER TABLE USERS ADD CONSTRAINT UQ_USERS_LOGIN UNIQUE (LOGIN_NAME);
ALTER TABLE USERS ADD CONSTRAINT CK_USERS_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'));

-- Optional stricter validation (recommended)
ALTER TABLE USERS ADD CONSTRAINT CK_USERS_LOGIN_NONEMPTY CHECK (LENGTH(TRIM(LOGIN_NAME)) > 0);
ALTER TABLE USERS ADD CONSTRAINT CK_USERS_EMAIL_NONEMPTY CHECK (LENGTH(TRIM(EMAIL)) > 0);



-- GROUPS
CREATE TABLE GROUPS (
  ID           NVARCHAR(36) PRIMARY KEY,
  NAME         NVARCHAR(255) NOT NULL,
  DISPLAY_NAME NVARCHAR(255) NOT NULL,
  DESCRIPTION  NVARCHAR(2000),

  IAS_LAST_MODIFIED TIMESTAMP,

  CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_UTCTIMESTAMP,
  UPDATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_UTCTIMESTAMP
);

ALTER TABLE GROUPS ADD CONSTRAINT UQ_GROUPS_NAME UNIQUE (NAME);


-- GROUP_MEMBERS (join table)
CREATE TABLE GROUP_MEMBERS (
  GROUP_ID   NVARCHAR(36) NOT NULL,
  USER_ID    NVARCHAR(36) NOT NULL,
  ADDED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_UTCTIMESTAMP,

  PRIMARY KEY (GROUP_ID, USER_ID),
  CONSTRAINT FK_GM_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_GM_USER  FOREIGN KEY (USER_ID)  REFERENCES USERS(ID)  ON DELETE CASCADE
);

CREATE INDEX IX_USERS_STATUS    ON USERS(STATUS);
CREATE INDEX IX_USERS_TYPE      ON USERS(USER_TYPE);
CREATE INDEX IX_USERS_LASTNAME  ON USERS(LAST_NAME);

CREATE INDEX IX_GROUPS_DISPLAY  ON GROUPS(DISPLAY_NAME);

CREATE INDEX IX_GM_USER         ON GROUP_MEMBERS(USER_ID);
CREATE INDEX IX_GM_GROUP        ON GROUP_MEMBERS(GROUP_ID);
